# Generated by Django 5.2.7 on 2026-02-24 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('total_animais', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chegada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qtd', models.IntegerField()),
                ('origem', models.CharField(blank=True, max_length=120)),
                ('obs', models.CharField(blank=True, max_length=255)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chegadas', to='porktekapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Morte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qtd', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('obs', models.CharField(blank=True, max_length=255)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortes', to='porktekapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('obs', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes', to='porktekapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Racao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('obs', models.CharField(blank=True, max_length=255)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racoes', to='porktekapp.lote')),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('qtd', models.IntegerField()),
                ('destino', models.CharField(blank=True, max_length=120)),
                ('obs', models.CharField(blank=True, max_length=255)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='porktekapp.lote')),
            ],
        ),
    ]
